=== elisagc/egc_javascript_daw/xml/dtd/info-cartas.dtd
<!ELEMENT juegos (juego+)>
<!ELEMENT juego (anyo, duracion, edad, id, maxjugadores, minjugadores, nombre, portada)>
<!ELEMENT anyo (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT maxjugadores (#PCDATA)>
<!ELEMENT minjugadores (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT portada (#PCDATA)>

=== elisagc/egc_javascript_daw/xml/xml/info-cartas.xml
<?xml version="1.0" encoding="UTF-8"?>

   <!DOCTYPE juegos SYSTEM "../dtd/info-cartas.dtd">
   
<juegos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/info-cartas.xsd">
         <juego>
            <anyo>2014</anyo>
            <duracion>60</duracion>
            <edad>13</edad>
            <id>10</id>
            <maxjugadores>4</maxjugadores>
            <minjugadores>2</minjugadores>
            <nombre>Arcadia Quest</nombre>
            <portada>https://cf.geekdo-images.com/original/img/lB5mc2bDPP2fNjvnBJLkSQvM2ps=/0x0/pic2305263.jpg</portada>
         </juego>
         <juego>
            <anyo>2015</anyo>
            <duracion>60</duracion>
            <edad>14</edad>
            <id>11</id>
            <maxjugadores>4</maxjugadores>
            <minjugadores>2</minjugadores>
            <nombre>Blood Rage</nombre>
            <portada>https://cf.geekdo-images.com/imagepagezoom/img/1P0_P_IIjR0Z3o40SDRife-atvI=/fit-in/1200x900/filters:no_upscale()/pic2439223.jpg</portada>
         </juego>
         <juego>
            <anyo>2015</anyo>
            <duracion>30</duracion>
            <edad>14</edad>
            <id>12</id>
            <maxjugadores>2</maxjugadores>
            <minjugadores>2</minjugadores>
            <nombre>Gwent: Monsters and Scoia'tael</nombre>
            <portada>https://cf.geekdo-images.com/original/img/He38WbxDGGgdFurPbYJlw_Ipx2A=/0x0/pic2794272.jpg</portada>
         </juego>
         <juego>
            <anyo>2017</anyo>
            <duracion>75</duracion>
            <edad>14</edad>
            <id>13</id>
            <maxjugadores>6</maxjugadores>
            <minjugadores>1</minjugadores>
            <nombre>Charterstone</nombre>
            <portada>https://cf.geekdo-images.com/original/img/QSEaUq4_I2KoVDrF1FGNJ7eAINs=/0x0/pic3322613.jpg</portada>
         </juego>
         <juego>
            <anyo>2018</anyo>
            <duracion>90</duracion>
            <edad>7</edad>
            <id>14</id>
            <maxjugadores>4</maxjugadores>
            <minjugadores>2</minjugadores>
            <nombre>Stuffed Fables</nombre>
            <portada>https://cf.geekdo-images.com/original/img/_qm1FBu5oN7XcONKTjUR1fz7ja8=/0x0/pic3708878.jpg</portada>
         </juego>
         <juego>
            <anyo>2016</anyo>
            <duracion>60</duracion>
            <edad>14</edad>
            <id>15</id>
            <maxjugadores>4</maxjugadores>
            <minjugadores>2</minjugadores>
            <nombre>Enchanters</nombre>
            <portada>https://cf.geekdo-images.com/original/img/Kzii7WDr_4aoVxa8Sylq7oFwCs4=/0x0/pic3710565.png</portada>
         </juego>
         <juego>
            <anyo>2012</anyo>
            <duracion>120</duracion>
            <edad>14</edad>
            <id>16</id>
            <maxjugadores>5</maxjugadores>
            <minjugadores>2</minjugadores>
            <nombre>Descent: Journeys in the Dark (Second Edition)</nombre>
            <portada>https://cf.geekdo-images.com/original/img/jGVm6aG5Ek-qxTIaWyzN67jjylc=/0x0/pic1180640.jpg</portada>
         </juego>
         <juego>
            <anyo>2018</anyo>
            <duracion>40</duracion>
            <edad>8</edad>
            <id>17</id>
            <maxjugadores>6</maxjugadores>
            <minjugadores>2</minjugadores>
            <nombre>Dice Throne: Season One</nombre>
            <portada>https://cf.geekdo-images.com/original/img/F9dqwWarGMc1nXIBqxs3FlipqTM=/0x0/pic3962955.jpg</portada>
         </juego>
         <juego>
            <anyo>2008</anyo>
            <duracion>30</duracion>
            <edad>8</edad>
            <id>18</id>
            <maxjugadores>6</maxjugadores>
            <minjugadores>3</minjugadores>
            <nombre>Dixit</nombre>
            <portada>https://cf.geekdo-images.com/original/img/m74nctbYaqTy03r8s_i_KTyvbYQ=/0x0/pic3483909.jpg</portada>
         </juego>
         <juego>
            <anyo>2012</anyo>
            <duracion>120</duracion>
            <edad>14</edad>
            <id>19</id>
            <maxjugadores>5</maxjugadores>
            <minjugadores>2</minjugadores>
            <nombre>Descent: Journeys in the Dark (Second Edition)</nombre>
            <portada>https://cf.geekdo-images.com/original/img/jGVm6aG5Ek-qxTIaWyzN67jjylc=/0x0/pic1180640.jpg</portada>
         </juego>
         <juego>
            <anyo>2014</anyo>
            <duracion>120</duracion>
            <edad>13</edad>
            <id>20</id>
            <maxjugadores>5</maxjugadores>
            <minjugadores>2</minjugadores>
            <nombre>Dead of Winter: A Crossroads Game</nombre>
            <portada>https://cf.geekdo-images.com/original/img/pOYQOSR1CnXcN6pEPx3yFDjKFaA=/0x0/pic3016500.jpg</portada>
         </juego>
         <juego>
            <anyo>2013</anyo>
            <duracion>240</duracion>
            <edad>14</edad>
            <id>21</id>
            <maxjugadores>8</maxjugadores>
            <minjugadores>1</minjugadores>
            <nombre>Eldritch Horror</nombre>
            <portada>https://cf.geekdo-images.com/original/img/i0zxc-H4TlTFB-yE1v4gcLy3XfY=/0x0/pic1872452.jpg</portada>
         </juego>
         <juego>
            <anyo>2014</anyo>
            <duracion>45</duracion>
            <edad>14</edad>
            <id>22</id>
            <maxjugadores>2</maxjugadores>
            <minjugadores>2</minjugadores>
            <nombre>Warhammer 40,000: Conquest</nombre>
            <portada>https://cf.geekdo-images.com/original/img/hq0ci9WVOrlud63_Of0gZeMzGPI=/0x0/pic2079275.jpg</portada>
         </juego>
         <juego>
            <anyo>2015</anyo>
            <duracion>60</duracion>
            <edad>10</edad>
            <id>23</id>
            <maxjugadores>6</maxjugadores>
            <minjugadores>1</minjugadores>
            <nombre>Zombicide Black Plague</nombre>
            <portada>https://cf.geekdo-images.com/imagepage/img/4LL0jzoz8mE_L8t8uBYCKd9REbE=/fit-in/900x600/filters:no_upscale()/pic2482309.jpg</portada>
         </juego>
         <juego>
            <anyo>2012</anyo>
            <duracion>60</duracion>
            <edad>7</edad>
            <id>24</id>
            <maxjugadores>4</maxjugadores>
            <minjugadores>1</minjugadores>
            <nombre>Mice and Mystics</nombre>
            <portada>https://cf.geekdo-images.com/imagepage/img/UOIYwkKb10yGzYW9MCZILrFhLVM=/fit-in/900x600/filters:no_upscale()/pic1312072.jpg</portada>
         </juego>
         <juego>
            <anyo>2014</anyo>
            <duracion>120</duracion>
            <edad>14</edad>
            <id>25</id>
            <maxjugadores>5</maxjugadores>
            <minjugadores>2</minjugadores>
            <nombre>Star Wars: Imperial Assault</nombre>
            <portada>https://cf.geekdo-images.com/original/img/wWTlEaPbVoUybefxFpFVTv1OU74=/0x0/pic2247647.jpg</portada>
         </juego>
         <juego>
            <anyo>2016</anyo>
            <duracion>60</duracion>
            <edad>14</edad>
            <id>26</id>
            <maxjugadores>4</maxjugadores>
            <minjugadores>2</minjugadores>
            <nombre>Inis</nombre>
            <portada>https://cf.geekdo-images.com/imagepage/img/c6vFqiWZr3ix-2rMkUA0idcaOfk=/fit-in/900x600/filters:no_upscale()/pic3112623.jpg</portada>
         </juego>
         <juego>
            <anyo>2009</anyo>
            <duracion>30</duracion>
            <edad>12</edad>
            <id>27</id>
            <maxjugadores>2</maxjugadores>
            <minjugadores>2</minjugadores>
            <nombre>Jaipur</nombre>
            <portada>https://cf.geekdo-images.com/original/img/3vpzUdiH5LopjHyHw8tHaspsWzk=/0x0/pic4679319.jpg</portada>
         </juego>
         <juego>
            <anyo>2012</anyo>
            <duracion>120</duracion>
            <edad>13</edad>
            <id>28</id>
            <maxjugadores>5</maxjugadores>
            <minjugadores>2</minjugadores>
            <nombre>Kemet</nombre>
            <portada>https://cf.geekdo-images.com/original/img/rjuKOHsH4_EayHV5jflH0LMpwqI=/0x0/pic3979527.jpg</portada>
         </juego>
         <juego>
            <anyo>2011</anyo>
            <duracion>30</duracion>
            <edad>8</edad>
            <id>29</id>
            <maxjugadores>6</maxjugadores>
            <minjugadores>2</minjugadores>
            <nombre>King of Tokyo</nombre>
            <portada>https://cf.geekdo-images.com/original/img/ajEqmO5djVibsC72Ek1citOCJNA=/0x0/pic3043734.jpg</portada>
         </juego>
         <juego>
            <anyo>2015</anyo>
            <duracion>15</duracion>
            <edad>14</edad>
            <id>30</id>
            <maxjugadores>8</maxjugadores>
            <minjugadores>2</minjugadores>
            <nombre>Codenames</nombre>
            <portada>https://cf.geekdo-images.com/original/img/MJ6MNz8-_rb1C2VUTnYBTYOiiy0=/0x0/pic2582929.jpg</portada>
         </juego>
         <juego>
            <anyo>2009</anyo>
            <duracion>30</duracion>
            <edad>13</edad>
            <id>31</id>
            <maxjugadores>10</maxjugadores>
            <minjugadores>5</minjugadores>
            <nombre>The Resistance</nombre>
            <portada>https://cf.geekdo-images.com/original/img/VDXFwn8wDc4yObdS5kUABZK6nhI=/0x0/pic2576459.jpg</portada>
         </juego>
         <juego>
            <anyo>2017</anyo>
            <duracion>120</duracion>
            <edad>12</edad>
            <id>32</id>
            <maxjugadores>4</maxjugadores>
            <minjugadores>1</minjugadores>
            <nombre>Lisboa</nombre>
            <portada>https://cf.geekdo-images.com/original/img/k4JCDnjnu5YRn5QA8njFeRMbulk=/0x0/pic3209553.jpg</portada>
         </juego>
         <juego>
