=== elisagc/egc_javascript_daw/xml/dtd/juegos.dtd
<!ELEMENT juegos (juego+)>
<!ELEMENT juego (imagen, nombre, descripcion, anyo, minimo_jugadores, maximo_jugadores, tiempo_minimo, tiempo_maximo, edad_minima)>
<!ATTLIST juego
          id CDATA #REQUIRED
          type CDATA #REQUIRED>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ATTLIST anyo
          value CDATA #REQUIRED>
<!ELEMENT minimo_jugadores (#PCDATA)>
<!ATTLIST minimo_jugadores
          value CDATA #REQUIRED>
<!ELEMENT maximo_jugadores (#PCDATA)>
<!ATTLIST maximo_jugadores
          value CDATA #REQUIRED>
<!ELEMENT tiempo_minimo (#PCDATA)>
<!ATTLIST tiempo_minimo
          value CDATA #REQUIRED>
<!ELEMENT tiempo_maximo (#PCDATA)>
<!ATTLIST tiempo_maximo
          value CDATA #REQUIRED>
<!ELEMENT edad_minima (#PCDATA)>
<!ATTLIST edad_minima
          value CDATA #REQUIRED>

=== elisagc/egc_javascript_daw/xml/juegos.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="juegos.xsl"?>

<!DOCTYPE juegos SYSTEM "dtd/juegos.dtd">

<juegos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/juegos.xsd">

	<juego type="boardgame" id="1">
		<imagen>https://cf.geekdo-images.com/original/img/IEzLo1POAmIfu9lyOvXsQxtVfB0=/0x0/pic3584961.jpg</imagen>
		<nombre>10 Minute Heist</nombre>
		<descripcion>The Wizard's Tower, players take turns moving their pawns from room to room stealing items. Players compete for most paintings, artifacts, jewels, and fossils. Players also compete for the most items valued at 3, 4, and 5. The first player to exit receives bonus points, so it's a race to the finish while simultaneously trying to get sets of items to maximize points. Be careful not to accumulate too many cursed items because they're worth negative points at the end of the game; </descripcion>
		<anyo value="2017"/>
		<minimo_jugadores value="2"/>
		<maximo_jugadores value="5"/>
		<tiempo_minimo value="10"/>
		<tiempo_maximo value="10"/>
		<edad_minima value="14"/>
	</juego>

	<juego type="boardgame" id="2">
		<imagen>https://cf.geekdo-images.com/original/img/M6wL1YFgW-PsdtJ328m2QiJf1K8=/0x0/pic3376065.jpg</imagen>
		<nombre>7 Wonders Duel</nombre>
		<descripcion>In many ways 7 Wonders Duel resembles its parent game 7 Wonders as over three ages players acquire cards that provide resources or advance their military or scientific development in order to develop a civilization and complete wonders; What's different about 7 Wonders Duel is that, as the title suggests, the game is solely for two players, with the players not drafting cards simultaneously from hands of cards, but from a display of face-down and face-up cards arranged at the start of a round. A player can take a card only if it's not covered by any others, so timing comes into play as well as bonus moves that allow you to take a second card immediately. As in the original game, each card that you acquire can be built, discarded for coins, or used to construct a wonder; Each player starts with four wonder cards, and the construction of a wonder provides its owner with a special ability. Only seven wonders can be built, though, so one player will end up short; Players can purchase resources at any time from the bank, or they can gain cards during the game that provide them with resources for future building; as you acquire resources, the cost for those particular resources increases for your opponent, representing your dominance in this area; A player can win 7 Wonders Duel in one of three ways: each time you acquire a military card, you advance the military marker toward your opponent's capital, giving you a bonus at certain positions; if you reach the opponent's capital, you win the game immediately; similarly, if you acquire any six of seven different scientific symbols, you achieve scientific dominance and win immediately; if none of these situations occurs, then the player with the most points at the end of the game wins; </descripcion>
		<anyo value="2015"/>
		<minimo_jugadores value="2"/>
		<maximo_jugadores value="2"/>
		<tiempo_minimo value="30"/>
		<tiempo_maximo value="30"/>
		<edad_minima value="10"/>
	</juego>

	<juego type="boardgame" id="3">
		<imagen>https://cf.geekdo-images.com/original/img/AG4FQZuzzueBT6t31kypY8jTRus=/0x0/pic2398773.jpg</imagen>
		<nombre>Above and Below</nombre>
		<descripcion>Your last village was ransacked by barbarians. You barely had time to pick up the baby and your favorite fishing pole before they started the burning and pillaging. You wandered over a cruel desert, braved frozen peaks, and even paddled a log across a rough sea, kicking at the sharks whenever they got too close, the baby strapped tightly to your back; Then you found it! The perfect place to make your new home. But as soon as you had the first hut built, you discovered a vast network of caverns underground, brimming with shiny treasures, rare resources, and untold adventure. How could you limit your new village to the surface? You immediately start organizing expeditions and building houses underground as well as on the surface; With any luck, you'll build a village even stronger than your last-- strong enough, even, to turn away the barbarians the next time they come knocking; Above and Below is a mashup of town-building and storytelling where you and up to three friends compete to build the best village above and below ground. In the game, you send your villagers to perform jobs like exploring the cave, harvesting resources, and constructing houses. Each villager has unique skills and abilities, and you must decide how to best use them. You have your own personal village board, and you slide the villagers on this board to various areas to indicate that they've been given jobs to do. Will you send Hanna along on the expedition to the cave? Or should she instead spend her time teaching important skills to one of the young villagers; A great cavern lies below the surface, ready for you to explore-- this is where the storytelling comes in. When you send a group of villagers to explore the depths, one of your friends reads what happens to you from a book of paragraphs. You'll be given a choice of how to react, and a lot will depend on which villagers you brought on the expedition, and who you're willing to sacrifice to succeed. The book of paragraphs is packed with encounters of amazing adventure, randomly chosen each time you visit the cavern; At the end of the game, the player with the most well-developed village wins; The Kickstarter version of the game included the following items which are not found in the Retail version;      Villager Tool token;      Lost Villager;      Swamp Villager;      Exclusive Stretch goals;      Creature Villager;      Quest Token;      Underforest Tokens and PDF story boo;      Desert Labyrinth tokens and PDF story book;      Wooden Good; This collection of items can be found in Above and Below: Expanded Edition exclusive; </descripcion>
		<anyo value="2015"/>
		<minimo_jugadores value="2"/>
		<maximo_jugadores value="4"/>
		<tiempo_minimo value="90"/>
		<tiempo_maximo value="90"/>
		<edad_minima value="13"/>
	</juego>

	<juego type="boardgame" id="4">
		<imagen>https://cf.geekdo-images.com/original/img/lB5mc2bDPP2fNjvnBJLkSQvM2ps=/0x0/pic2305263.jpg</imagen>
		<nombre>Arcadia Quest</nombre>
		<descripcion>In Arcadia Quest, players lead guilds of intrepid heroes on an epic campaign to dethrone the vampire lord and reclaim the mighty Arcadia for their own. But only one guild may lead in the end, so players must battle against each other as well as against the monstrous occupying forces; Arcadia Quest is a campaign-based game for 2 to 4 players, where each player controls a guild of three unique heroes, facing off against the other players and the various monsters controlled by the game. Players need to accomplish a series of quests in order to win each scenario and choose where to go next in the campaign; Players are able to choose the path their campaign takes, navigating through six out of eleven available scenarios, so each time the campaign is played it can have a different configuration of scenarios. As the campaign progresses, the heroes are able to acquire new weapons, equipment and abilities that give them powerful options to tackle the obstacles ahead. Furthermore, by fulfilling specific quests in a scenario, players unlock exclusive features in subsequent scenarios; </descripcion>
		<anyo value="2014"/>
		<minimo_jugadores value="2"/>
		<maximo_jugadores value="4"/>
		<tiempo_minimo value="60"/>
		<tiempo_maximo value="60"/>
		<edad_minima value="13"/>
	</juego>

	<juego type="boardgame" id="5">
		<imagen>https://cf.geekdo-images.com/original/img/EQ0Kl-bH9RCI5aJWVLnAlAfo00E=/0x0/pic3122349.jpg</imagen>
		<nombre>Arkham Horror: LCG</nombre>
		<descripcion>Description from the publisher; Something evil stirs in Arkham, and only you can stop it. Blurring the traditional lines between roleplaying and card game experiences, Arkham Horror: The Card Game is a Living Card Game of Lovecraftian mystery, monsters, and madness; In the game, you and your friend (or up to three friends with two Core Sets) become characters within the quiet New England town of Arkham. You have your talents, sure, but you also have your flaws. Perhaps you've dabbled a little too much in the writings of the Necronomicon, and its words continue to haunt you. Perhaps you feel compelled to cover up any signs of otherworldly evils, hampering your own investigations in order to protect the quiet confidence of the greater population. Perhaps you'll be scarred by your encounters with a ghoulish cult; No matter what compels you, no matter what haunts you, you'll find both your strengths and weaknesses reflected in your custom deck of cards, and these cards will be your resources as you work with your friends to unravel the world's most terrifying mysteries; Each of your adventures in Arkham Horror LCG carries you deeper into mystery. You'll find cultists and foul rituals. You'll find haunted houses and strange creatures. And you may find signs of the Ancient Ones straining against the barriers to our world..; The basic mode of play in Arkham LCG is not the adventure, but the campaign. You might be scarred by your adventures, your sanity may be strained, and you may alter Arkham's landscape, burning buildings to the ground. All your choices and actions have consequences that reach far beyond the immediate resolution of the scenario at hand &amp;mdash; and your actions may earn you valuable experience with which you can better prepare yourself for the adventures that still lie before you; </descripcion>
		<anyo value="2016"/>
		<minimo_jugadores value="1"/>
		<maximo_jugadores value="2"/>
		<tiempo_minimo value="60"/>
		<tiempo_maximo value="120"/>
		<edad_minima value="14"/>
	</juego>
